config/routes.rb
NoActiveRecord::Application.routes.draw do
  
  get 'searchbydescriptions/' => 'searchbydescriptions#index'
  post 'searchbydescriptions/go' => 'searchbydescriptions#go'

  get 'searchbydatabasesources/' => 'searchbydatabasesources#index'
  post 'searchbydatabasesources/go' => 'searchbydatabasesources#go'

  get 'searchbyblasts/' => 'searchbyblasts#index'
  post 'searchbyblasts/go' => 'searchbyblasts#go'

  
  get 'searchbyorganisms/' => 'searchbyorganisms#index'
  post 'searchbyorganisms/go' => 'searchbyorganisms#go'

  
  get 'details/:id/show' => 'details#show'
  

  resources :orthologs

  root 'home#index'

end

app/models/orthologs.rb
class Orthologs < ActiveRecord::Base
end

app/models/searchbydescription.rb
class Searchbydescription < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController

  def show
    group_id = params['id']
    @root = Orthologs.where("group_id = '#{group_id}'").order(:organism_name)

    
  end


end

app/controllers/home_controller.rb
require 'cassandra/Keyspace'
require 'cassandra/Queries'

class HomeController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception
    skip_before_filter :verify_authenticity_token

    layout "application"

    def index
        @groups = Orthologs.all.size
    end

   
end

app/controllers/orthologs_controller.rb
class OrthologsController < ApplicationController
	def index
		@version = "1.0"

		@orthologs = Orthologs.all
	end
end

app/controllers/searchbyblasts_controller.rb
class SearchbyblastsController < ApplicationController
  before_action :set_searchbydescription, only: [:show, :edit, :update, :destroy]

  require 'OrthologsTree'

 # layout 'application'

  # GET /searchbydescriptions
  # GET /searchbydescriptions.json
  def index
      @groups = Orthologs.all.size
  end

   def go
      desc = params['protein_descriptions']
      @ids = Orthologs.where("protein_description like '%#{desc}%'").order(:source_db, :group_id, :protein_description)

      @root = OrthologsTree.new(nil, 'orthologs')
      #@root << 'kegg'
      #@root << 'eggnog'
      #@root << 'protozoa'

      @ids.each do |reg|
        if reg['source_db'] == 'KEGG'
          @root <<  reg['group_id'] << 'kegg'  << reg['organism_name']
        elsif reg['source_db'] == 'EGGNOG'
          @root << reg['group_id'] << 'eggnog' << reg['organism_name']
        elsif reg['source_db'] == 'PROTOZOADB'  
          @root << reg['group_id'] << 'protozoa' << reg['organism_name']
        end
      end
      
    end
end

app/controllers/searchbydatabasesources_controller.rb
class SearchbydatabasesourcesController < ApplicationController
  before_action :set_searchbydescription, only: [:show, :edit, :update, :destroy]

  require 'OrthologsTree'

 # layout 'application'

  # GET /searchbydescriptions
  # GET /searchbydescriptions.json
  def index
      @groups = Orthologs.all.size
  end

   def go
      desc = params['protein_descriptions']
      @ids = Orthologs.where("protein_description like '%#{desc}%'").order(:source_db, :group_id, :protein_description)

      @root = OrthologsTree.new(nil, 'orthologs')
      #@root << 'kegg'
      #@root << 'eggnog'
      #@root << 'protozoa'

      @ids.each do |reg|
        if reg['source_db'] == 'KEGG'
          @root <<  reg['group_id'] << 'kegg'  << reg['organism_name']
        elsif reg['source_db'] == 'EGGNOG'
          @root << reg['group_id'] << 'eggnog' << reg['organism_name']
        elsif reg['source_db'] == 'PROTOZOADB'  
          @root << reg['group_id'] << 'protozoa' << reg['organism_name']
        end
      end
      
    end
end

app/controllers/searchbydescriptions_controller.rb
class SearchbydescriptionsController < ApplicationController
  before_action :set_searchbydescription, only: [:show, :edit, :update, :destroy]

  require 'OrthologsTree'

 # layout 'application'

  # GET /searchbydescriptions
  # GET /searchbydescriptions.json
  def index
      @groups = Orthologs.all.size
  end

   def go
      desc = params['protein_descriptions']
      @ids = Orthologs.where("protein_description like '%#{desc}%'").order(:source_db, :group_id, :protein_description)

      @root = OrthologsTree.new(nil, 'orthologs')
      #@root << 'kegg'
      #@root << 'eggnog'
      #@root << 'protozoa'

      @ids.each do |reg|
        if reg['source_db'] == 'KEGG'
          @root <<  reg['group_id'] << 'kegg'  << reg['organism_name']
        elsif reg['source_db'] == 'EGGNOG'
          @root << reg['group_id'] << 'eggnog' << reg['organism_name']
        elsif reg['source_db'] == 'PROTOZOADB'  
          @root << reg['group_id'] << 'protozoa' << reg['organism_name']
        end
      end
      
    end
end

app/controllers/searchbyorganisms_controller.rb
class SearchbyorganismsController < ApplicationController
  require 'OrthologsTree'

 def index
      @groups = Orthologs.all.size
  end

   def go
      org = params['organism']
      @ids = Orthologs.find_by_sql("select * from orthologs where group_id in (select group_id from orthologs where organism_name like '%#{org}%')")

      @root = OrthologsTree.new(nil, 'orthologs')
      #@root << 'kegg'
      #@root << 'eggnog'
      #@root << 'protozoa'

      @ids.each do |reg|
        if reg['source_db'] == 'KEGG'
          @root <<  reg['group_id'] << 'kegg'  << reg['organism_name']
        elsif reg['source_db'] == 'EGGNOG'
          @root << reg['group_id'] << 'eggnog' << reg['organism_name']
        elsif reg['source_db'] == 'PROTOZOADB'  
          @root << reg['group_id'] << 'protozoa' << reg['organism_name']
        end
      end
      
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orthologs_helper.rb
module OrthologsHelper
end

app/helpers/searchbydescriptions_helper.rb
module SearchbydescriptionsHelper
end

app/views/details/show.html.erb
<div class="container row">
<h4>Details</h4>
<ul class="DETAILS ">

<%@root.each do |r|%>
    <li class="<%=r['source_db']%> " title="<%=r['source_db']%>" alt="<%=r['source_db']%>"><%=r['protein_id']%> (<%=r['organism_name']%>)</li>
<%end%>
</ul>
<hr>
</div>	

app/views/details/show.js.erb
$('#details').hide();
$('#details').html('<%= escape_javascript( render :file => "details/show.html.erb") %>');
$('#details').show(600);

app/views/home/getBySourceDB.html.erb
<form action="home/getBySourceDB" method="post">

<table border="1">
<%@rows.each do |row|%>
	<tr>
		<td>
			<%=row["group_id"]%>
		</td>
		<td>
			<%=row["group_description"]%>
		</td>
		<td>
			<%=row["protein_id"]%>
		</td>
		<td>
			<%=row["protein_description"]%>
		</td>
	</tr>
<%end%>
</table>

	<input type="text" id="sourcedb" name="sourcedb" />
	<input type="submit" value="kade?" />

</form>

app/views/home/getSourceDB.html.erb
<form action="home/getBySourceDB" method="post">

<table border="1">
<%@rows.each do |row|%>
	<tr>
		<td>
			<%=row["group_id"]%>
		</td>
		<td>
			<%=row["group_description"]%>
		</td>
		<td>
			<%=row["protein_id"]%>
		</td>
		<td>
			<%=row["protein_description"]%>
		</td>
	</tr>
<%end%>
</table>

	<input type="text" id="sourcedb" name="sourcedb" />
	<input type="submit" />

</form>

app/views/home/index.html.erb
<h1>Bigdata-based OrthoSearch DB</h1>  

<div class="span7">
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>
<div id="dna"></div>



 


 
 

app/views/home/show.html.erb
<!DOCTYPE html>
<html>
<HEAD>
<title>BigOrthoSearchDB</title>
<style>
a:link {text-decoration:none;}    /* unvisited link */
a:visited {text-decoration:none;} /* visited link */
a:hover {text-decoration:none;}   /* mouse over link */
a:active {text-decoration:none;}  /* selected link */
</style>
</HEAD>
<body>

<div style="margin-bottom:-10px">
   <h1 style="font:Magneto Bold; color:black; margin-top:15px;">
      <a href="home">BigOrthoSearchDB </a>
    </h1>
  <div style="margin-top:40px;">
   
  </div>
  <div style="margin-left:90%;color:black; width:150px;  margin-top:-70px;">
    <ul>
       <li>Statistics</li>
       <li>12.000 GO</li>
       <li>350.000 proteins</li>
    </ul>
  </div>  

</div>


<hr SIZE=7 NOSHADE COLOR="#rrggbb" style="margin-top:1%" > <!-- Linha horizontal -->
<br>
<br>
<label style= "margin-left:20%; font:Comic Sans; font-size:20px; font-weight:bold; color:black;"> Search by Description: </label>
<input type= "text">
<input type= "submit">

<br>
<br>
<br>

<img border="0" src="/images/fig1.jpg" alt="Arvore"> 
<br>

<div style="margin-left:85%; margin-top:-18%;">
<img border="0" src="/images/um anil.jpg" alt="H. Sapiens" width="35" height="35" style= "display: inline">
<label style="font:Magneto Bold; color:black; font-size: 18px;">H. Sapiens</label>
<br> 
<img border="0" src="/images/um verde.jpg" alt="T. Brucei " width="35" height="35">
<label style="font:Magneto Bold; color:black; font-size: 18px;">T. Brucei</label> 
<br>
<img border="0" src="/images/um amarelo.jpg" alt="T. Cruzi" width="35" height="35"> 
<label style="font:Magneto Bold; color:black; font-size: 18px;">T. Cruzi</label> 
<br>
<img border="0" src="/images/zero.jpg" alt="seila" width="35" height="35">
<br>
<img border="0" src="/images/tres.jpg" alt="seila" width="35" height="35">  
</div>
<br>

<hr style="margin-bottom:1%; margin-top:3%" SIZE=7 NOSHADE COLOR="#rrggbb"> <!-- Linha horizontal -->
<p style= "margin-left:40%; margin-bottom:-2%"> Biowebdb Consortiumn </p>
</body>
</html>

<%= link_to 'Back', home_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BOSDB</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/">BOSDB</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Search Description", searchbydescriptions_path %></li>
            <li><%= link_to "Search Organism", searchbyorganisms_path %></li>
            <li><%= link_to "Search Database Source", searchbydatabasesources_path %></li>
            <li><%= link_to "Search Blast", searchbyblasts_path  %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
<div id="wrap">
      <div class="container jumbotron">
        <% flash.each do |name, msg| %>
          <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
            <a class="close" data-dismiss="alert">×</a>
            <%= msg %>
          </div>
        <% end %>
      	<div class="row">
      		<div class=" span9"><%= yield %></div>	
        <div class=" span3">
            <h3>Statistics</h3>
            <span class="label label-warning"><%=@groups%> GO's</span> <br>
            <span class="label label-success">350.000 proteins</span>
          </div>   
        </div>
      </div>
</div>
<span class="row"></span>
<div id="footer">
      <div class="container row">
        <p>Biowebdb Consortiumn </p>
      </div>
    </div>
    
</body>
<%= javascript_include_tag "application" , controller_name %>
</html>

app/views/orthologs/index.html.erb
<h1>Orthologs</h1>

Version app: <%=@version%>

<table>
  <tr>
    <th>Group Id</th>
    <th>Protein Id</th>
  </tr>
 
  <% @orthologs.each do |ortho| %>
    <tr>
      <td><%= ortho.group_id %></td>
      <td><%= ortho.protein_id %></td>
    </tr>
  <% end %>
</table>

app/views/searchbyblasts/go.html.erb
<div class="container">
<h4> Results </h4>

<ul>
<%@root.family.each do |f|%>
    <%if f.parent == @root%>
        <li><%=link_to "#{f.value}", "/details/#{f.value}/show", :remote => true%></li>
    <%end%>
<%end%>
</ul>


<div id="details">
</div>
</div>

app/views/searchbyblasts/go.js.erb
$('#result').hide();
$('#result').html('<%= escape_javascript( render :file => "searchbyblasts/go.html.erb") %>');
$('#result').show(600);

app/views/searchbyblasts/index.html.erb
<h3>Search by Blast</h3>


<%= form_tag('/searchbyblasts/go', class:"form-search", :remote => true) do %>
<div class="input-append">
 <%= text_field_tag'protein_descriptions',  nil, placeholder:'Enter blast sequence',class:"span6 search-query"  %>
    <%=submit_tag 'Search', class:"btn" %>
</div>
<% end %>

<div id='result'>
</div>

app/views/searchbydatabasesources/go.html.erb
<div class="container">
<h4> Results </h4>

<ul>
<%@root.family.each do |f|%>
    <%if f.parent == @root%>
        <li><%=link_to "#{f.value}", "/details/#{f.value}/show", :remote => true%></li>
    <%end%>
<%end%>
</ul>


<div id="details">
</div>
</div>

app/views/searchbydatabasesources/go.js.erb
$('#result').hide();
$('#result').html('<%= escape_javascript( render :file => "searchbydatabasesources/go.html.erb") %>');
$('#result').show(600);

app/views/searchbydatabasesources/index.html.erb
<h3>Search by Database Source</h3>


<%= form_tag('/searchbydatabasesources/go', class:"form-search", :remote => true) do %>
<div class="input-append">
 <%= text_field_tag'protein_descriptions',  nil, placeholder:'Enter Database Source',class:"span6 search-query"  %>
    <%=submit_tag 'Search', class:"btn" %>
</div>
<% end %>

<div id='result'>
</div>

app/views/searchbydescriptions/go.html.erb
<h1> Results </h1>

<ul>
<%@root.family.each do |f|%>
    <%if f.parent == @root%>
        <li><%=link_to "#{f.value}", "/details/#{f.value}/show", :remote => true%></li>
    <%end%>
<%end%>
</ul>


<div id="details">
</div>

app/views/searchbydescriptions/go.js.erb
$('#result').hide();
$('#result').html('<%= escape_javascript( render :file => "searchbydescriptions/go.html.erb") %>');
$('#result').show(600);

app/views/searchbydescriptions/index.html.erb
<h3>Search by protein</h3>


<%= form_tag('/searchbydescriptions/go', class:"form-search", :remote => true) do %>
<div class="input-append">
 <%= text_field_tag'protein_descriptions',  nil, placeholder:'Enter protein name or part of name',class:"span6 search-query"  %>
    <%=submit_tag 'Search', class:"btn" %>
</div>
<% end %>

<div id='result'>
</div>

app/views/searchbyorganisms/alert('oḱ ');.erb
$('#result').hide();
$('#result').html('<%= escape_javascript( render :file => "searchbydescriptions/go.html.erb") %>');
$('#result').show(600);

app/views/searchbyorganisms/go.html.erb
<h4> Results </h4>

<ul>
<%@root.family.each do |f|%>
    <%if f.parent == @root%>
        <li><%=link_to "#{f.value}", "/details/#{f.value}/show", :remote => true%></li>
    <%end%>
<%end%>
</ul>


<div id="details">
</div>

app/views/searchbyorganisms/go.js.erb
$('#result').hide();
$('#result').html('<%= escape_javascript( render :file => "searchbyorganisms/go.html.erb") %>');
$('#result').show(600);

app/views/searchbyorganisms/index.html.erb
<h3>Search by organism</h3>


<%= form_tag('/searchbyorganisms/go', class:"form-search", :remote => true) do %>
<div class="input-append">
 <%= text_field_tag'organism',  nil, placeholder:'Enter organism name or part of name',class:"span6 search-query"  %>
    <%=submit_tag 'Search', class:"btn" %>
</div>
<% end %>

<div id='result'>
</div>